# Generated by Django 4.1.4 on 2023-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('fee', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
    ]
