# Generated by Django 4.1.4 on 2023-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='field',
            field=models.CharField(default='software', max_length=200),
        ),
    ]
