# Generated by Django 4.1.4 on 2023-08-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_courses_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('O', 'Other')], max_length=100)),
                ('dateofbirth', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=300)),
                ('proflepicture', models.FileField(upload_to='documents')),
            ],
        ),
    ]
