# Generated by Django 4.1.4 on 2023-08-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='0000', max_length=300),
        ),
    ]
