# Generated by Django 4.1.4 on 2023-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dateofbirth',
            field=models.CharField(default='00-00-0000', max_length=200),
        ),
    ]
