# Generated by Django 4.1.4 on 2023-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_registration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
