# Generated by Django 4.1.4 on 2023-08-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_registration_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opted_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('joindate', models.CharField(max_length=200)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.courses')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.registration')),
            ],
        ),
    ]
