# Generated by Django 4.1.4 on 2023-08-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_remove_registration_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.registration')),
            ],
        ),
    ]
