# Generated by Django 4.1.4 on 2023-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_temp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
