# Generated by Django 4.2.4 on 2023-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='proflepicture',
            field=models.FileField(upload_to=''),
        ),
    ]
