# Generated by Django 4.2.4 on 2023-09-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_alter_registration_proflepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dateofbirth',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='proflepicture',
            field=models.FileField(upload_to='documents'),
        ),
    ]
